vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       books_image:
           uri_prefix: /images/books
           upload_destination: '%kernel.project_dir%/public/images/books'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
